[package]
name = "zstar-desktop-shell"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
tauri-build = { version = "2.0.2", features = [] }

[dependencies]
zstar-app-host = { path = "../../../crates/app-host" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2.1.1", features = [] }
